Web/main/main/dlp/urls.py
from django.urls import path
from .views import *

app_name = "dlp"
urlpatterns = [
    path('dashboard/', dashboard_views, name="dashboard"),
    path('policy/', policy_views, name="policy"),
    path('rules/', rules_views, name="rules"),
    path('logs/', logs_views, name="logs"),

    # only superuser
    path('add_policy/', add_policy_views, name="add_policy"),
    path('update_policy/<int:id>/', update_policy_views, name="update_policy"),
    path('delete_policy/<int:id>/', delete_policy_views, name="delete_policy"),

    path('add_rule/', add_rule_views, name="add_rule"),
    path('update_rule/<int:id>/', update_rule_views, name="update_rule"),
    path('delete_rule/<int:id>/', delete_rule_views, name="delete_rule"),

    path('update_log/<int:id>/', update_log_views, name="update_log"),
    path('delete_log/<int:id>/', delete_log_views, name="delete_log"),

    # export
    path('export/log/excel/', logs_export_excel_views, name="logs_export_excel"),
    path('export/log/csv/', logs_export_csv_views, name="logs_export_csv"),
]

Web/main/main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('dlp/', include('dlp.urls')),

]

Web/main/main/dlp/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.


class Logs(models.Model):
    file_path = models.CharField(
        max_length=500, verbose_name="File Path")
    event_type = models.CharField(max_length=100, verbose_name="Event Type")
    created_date = models.DateTimeField(
        verbose_name="Created Date", auto_now_add=True)

    def __str__(self):
        return self.event_type

    def get_update_url(self):
        return reverse('dlp:update_log', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('dlp:delete_log', kwargs={'id': self.id})


class Rule(models.Model):
    PERMISSION = [
        ('N', 'No Access'),
        ('F', 'Full Accsess'),
        ('M', 'Modify access'),
        ('RX', 'Read and execute access'),
        ('R', 'Read-only access'),
        ('W', 'Write-only access'),
    ]

    ACCSESS = [
        ('grant', 'grant'),
        ('deny', 'deny'),
        ('remove', 'remove'),
        ('setintegritylevel', 'setintegritylevel'),
    ]

    name = models.CharField(max_length=50, verbose_name="Rule Name")
    permission = models.CharField(
        default="F", choices=PERMISSION, max_length=50)
    accsess = models.CharField(default="grant", choices=ACCSESS, max_length=50)
    created_date = models.DateTimeField(
        verbose_name="Created Date", auto_now_add=True)

    def __str__(self):
        return f"{self.name} ---> {self.permission} ---> {self.accsess}"

    def get_update_url(self):
        return reverse('dlp:update_rule', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('dlp:delete_rule', kwargs={'id': self.id})


class Policy(models.Model):
    name = models.CharField(
        max_length=500, verbose_name="Policy Name")
    logs = models.ManyToManyField(
        Logs, related_name="policy_logs", blank=True)
    rule = models.OneToOneField(Rule, on_delete=models.CASCADE)
    created_date = models.DateTimeField(
        verbose_name="Created Date", auto_now_add=True)

    def __str__(self):
        return f"{self.name} ---> {self.rule}"

    def get_update_url(self):
        return reverse('dlp:update_policy', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('dlp:delete_policy', kwargs={'id': self.id})

Web/main/main/dlp/forms.py
from django import forms
from .models import Logs, Policy, Rule


class PolicyCreateForm(forms.ModelForm):

    class Meta:
        model = Policy
        fields = ['name', 'logs', 'rule']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
        }


class PolicyUpdateForm(forms.ModelForm):

    class Meta:
        model = Policy
        fields = ['name', 'logs', 'rule']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
        }


class LogUpdateForm(forms.ModelForm):

    class Meta:
        model = Logs
        fields = ['file_path', 'event_type']
        widgets = {
            'file_path': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'event_type': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
        }


class RuleCreateForm(forms.ModelForm):

    class Meta:
        model = Rule
        fields = ['name', 'permission', 'accsess']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'permission': forms.Select(),
            'accsess': forms.Select(),
        }


class RuleUpdateForm(forms.ModelForm):

    class Meta:
        model = Rule
        fields = ['name', 'permission', 'accsess']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'permission': forms.Select(),
            'accsess': forms.Select(),
        }

Web/main/main/dlp/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import LogUpdateForm, PolicyCreateForm, PolicyUpdateForm, RuleCreateForm, RuleUpdateForm
from .models import Logs, Policy, Rule

import csv
import xlwt

from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


@login_required
def dashboard_views(request):

    return render(request, "dlp/dashboard.html")


@login_required
def policy_views(request):
    policy = Policy.objects.all()
    context = {
        'policy': policy
    }
    return render(request, "dlp/policy.html", context)


@login_required
def rules_views(request):
    rules = Rule.objects.all()
    context = {
        'rules': rules
    }
    return render(request, "dlp/rules.html", context)


@login_required
def logs_views(request):
    log_list = Logs.objects.all()

    paginator = Paginator(log_list, 15)  # Show 15 contacts per page

    page = request.GET.get('q')
    try:
        logs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        logs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        logs = paginator.page(paginator.num_pages)

    query = request.GET.get('q')
    if query:
        logs = log_list.filter(
            Q(file_path__icontains=query) | Q(event_type__icontains=query)).distinct()
    context = {
        'logs': logs
    }
    return render(request, "dlp/logs.html", context)

# only superuser


@login_required
def add_policy_views(request):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    if request.method == 'POST':
        policy_form = PolicyCreateForm(request.POST)
        if policy_form.is_valid():
            policy_form.save()
            messages.success(request, 'Policy has been created!')
            return redirect('dlp:policy')
        else:
            return render(request, 'dlp/post/add_policy.html', {'form': policy_form})

    policy_form = PolicyCreateForm(request.POST)
    return render(request, "dlp/post/add_policy.html", {'form': policy_form})


@login_required
def update_policy_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")
    instance = Policy.objects.get(pk=id)
    policy_form = PolicyUpdateForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if policy_form.is_valid():
            policy_form.save()
            messages.success(request, 'Policy has been updated!', {
                             'form': policy_form})
            return redirect('dlp:policy')
        else:
            return render(request, 'dlp/post/update_policy.html', {'form': policy_form})

    return render(request, "dlp/post/update_policy.html", {'form': policy_form})


@login_required
def delete_policy_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    policy = Policy.objects.get(id=id)
    try:
        policy.delete()
        messages.success(request, "Policy has been successfully deleted.")
    except:
        messages.error(request, "Policy could not be deleted!")

    return redirect('dlp:policy')


@login_required
def add_rule_views(request):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")
    rule_form = RuleCreateForm(request.POST or None)

    if request.method == 'POST':
        if rule_form.is_valid():
            rule_form.save()
            messages.success(request, 'Rule has been created!')
            return redirect('dlp:rules')
        else:
            return render(request, 'dlp/post/add_rule.html', {'form': rule_form})

    return render(request, 'dlp/post/add_rule.html', {'form': rule_form})


@login_required
def update_rule_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    instance = Rule.objects.get(id=id)
    rule_form = RuleUpdateForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if rule_form.is_valid():
            rule_form.save()
            messages.success(request, 'Rule has been updated!')
            return redirect('dlp:rules')
        else:
            return render(request, 'dlp/post/update_rule.html', {'form': rule_form})

    return render(request, 'dlp/post/update_rule.html', {'form': rule_form})


@login_required
def delete_rule_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    rule = Rule.objects.get(id=id)
    try:
        rule.delete()
        messages.success(request, "Rule has been successfully deleted.")
    except:
        messages.error(request, "Rule could not be deleted!")

    return redirect('dlp:rules')


@login_required
def update_log_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    instance = Logs.objects.get(id=id)
    log_form = LogUpdateForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if log_form.is_valid():
            log_form.save()
            messages.success(request, 'Log has been updated!')
            return redirect('dlp:logs')
        else:
            return render(request, 'dlp/post/update_log.html', {'form': log_form})

    return render(request, 'dlp/post/update_log.html', {'form': log_form})


@login_required
def delete_log_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    log = Logs.objects.get(id=id)
    try:
        log.delete()
        messages.success(request, "Log has been successfully deleted.")
    except:
        messages.error(request, "Log could not be deleted!")

    return redirect('dlp:logs')

# export


def logs_export_csv_views(request):

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=Logs_' + \
        str(datetime.now()) + '.csv'

    writer = csv.writer(response)
    writer.writerow(['Date', 'Source', 'Rule Type', 'Details'])

    logs = Logs.objects.all()

    for log in logs:
        writer.writerow([log.created_date, log.file_path,
                        log.rule_type, log.event_type])

    return response


def logs_export_excel_views(request):

    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=Logs_' + \
        str(datetime.now()) + '.xls'

    wb = xlwt.Workbook(encoding='utf*8')
    ws = wb.add_sheet('Logs')
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['Date', 'Source', 'Rule Type', 'Details']

    logs = Logs.objects.all()
    #  ws.write([log.created_date, log.file_path, log.rule_type, log.event_type])
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    rows = Logs.objects.all().values_list(
        'created_date', 'file_path', 'rule_type', 'event_type')

    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, str(rows[col_num]), font_style)

    wb.save(response)

    return response

Web/main/main/templates/dlp/logs.html
{% extends 'base/admin/base.html' %}
{% block content %}
<!-- Page Wrapper -->
<div id="wrapper">
    
    {% include 'base/admin/sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            {% include 'base/admin/topbar.html' %}

            <!-- Begin Page Content -->
            <div class="container-fluid">
                {% include 'base/message.html' %}

                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">LOGS</h1>
                <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                        href="https://datatables.net">official DataTables documentation</a>.</p>
                
                <!-- Logs Table -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Logs</h6>    
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="#" class="btn btn-success btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-flag"></i>
                                </span>
                                <span class="text">Detailed Search</span>
                            </a>
                            <a href="{% url 'dlp:logs_export_excel' %}" class="btn btn-primary ml-1 btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-flag"></i>
                                </span>
                                <span class="text">Export to Excel</span>
                            </a>
                            <a href="{% url 'dlp:logs_export_csv' %}" class="btn btn-primary ml-1 btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-flag"></i>
                                </span>
                                <span class="text">Export to CSV</span>
                            </a>
                            <a href="{% url 'dlp:logs' %}" class="btn btn-danger ml-1 btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-flag"></i>
                                </span>
                                <span class="text">Refresh</span>
                            </a>
                            <!-- Topbar Search -->
                            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" method="get">
                            <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small" name="q" value="{{request.GET.q}}" placeholder="Search logs..."
                                    aria-label="Search" aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-info" type="submit">
                                        <i class="fas fa-search fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                          </div>
                    </div>
                    
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>File Path</th>
                                        {% if request.user.is_superuser %}
                                            <th>Action</th>
                                        {% endif %}
                                        <th>Event Type</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Date</th>
                                        <th>File Path</th>
                                        {% if request.user.is_superuser %}
                                            <th>Action</th>
                                        {% endif %}
                                        <th>Event Type</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    {% for log in logs %}
                                    <tr>
                                        <td>{{log.created_date|date:"M d, Y"}}</td>
                                        <td>{{log.file_path}}</td>
                                        {% if request.user.is_superuser %}
                                            <td>
                                                <a href="{{log.get_update_url}}" class="btn btn-primary ml-1 btn-icon-split btn-sm">
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-flag"></i>
                                                    </span>
                                                    <span class="text">Edit</span>
                                                </a>
                                                <a href="{{log.get_delete_url}}" class="btn btn-danger ml-1 btn-icon-split btn-sm">
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-flag"></i>
                                                    </span>
                                                    <span class="text">Delete</span>
                                                </a>
                                            </td>
                                        {% endif %}
                                        <td>{{log.event_type}}</td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                      <!--Pagination-->
      <div class="pagination mt-5">
        <span class="step-links">
            {% if logs.has_previous %}
                <a href="?page={{ logs.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ logs.number }} of {{ logs.paginator.num_pages }}.
            </span>
            {% if logs.has_next %}
                <a href="?page={{ logs.next_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">next</a>
            {% endif %}
        </span>
      </div>
    <!--end of Pagination-->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        {% include 'base/admin/footer.html' %}

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
{% endblock content %}

Web/main/main/templates/dlp/policy.html
{% extends 'base/admin/base.html' %}
{% block content %}
<!-- Page Wrapper -->
<div id="wrapper">
    {% include 'base/admin/sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            {% include 'base/admin/topbar.html' %}

            <!-- Begin Page Content -->
            <div class="container-fluid">
                {% include 'base/message.html' %}

                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">POLICY</h1>
                <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                        href="https://datatables.net">official DataTables documentation</a>.</p>
                
                <!-- Policy Table -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Policy</h6>    
                        {% if request.user.is_superuser %}
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="{% url 'dlp:add_policy' %}" class="btn btn-success btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-flag"></i>
                                </span>
                                <span class="text">Add</span>
                            </a>
                          </div>
                        {% endif %}

                    </div>
                    
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Policy Name</th>
                                        <th>Logs Count</th>
                                        <th>Rule</th>
                                         {% if request.user.is_superuser %}
                                            <th>Action</th>
                                        {% endif %}
                                        <th>Created Date</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Policy Name</th>
                                        <th>Logs Count</th>
                                        <th>Rule</th>
                                        {% if request.user.is_superuser %}
                                            <th>Action</th>
                                        {% endif %}
                                        <th>Created Date</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    {% for item in policy %}
                                    <tr>
                                        <td>{{item.name}}</td>
                                        <td>{{item.logs.count}}</td>
                                        <td>{{item.rule}}</td>
                                        {% if request.user.is_superuser %}
                                            <td>
                                                <a href="{{item.get_update_url}}" class="btn btn-primary ml-1 btn-icon-split btn-sm">
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-flag"></i>
                                                    </span>
                                                    <span class="text">Edit</span>
                                                </a>
                                                <a href="{{item.get_delete_url}}" class="btn btn-danger ml-1 btn-icon-split btn-sm">
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-flag"></i>
                                                    </span>
                                                    <span class="text">Delete</span>
                                                </a>
                                            </td>
                                        {% endif %}
                                        <td>{{item.created_date}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        {% include 'base/admin/footer.html' %}

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
{% endblock content %}