Web/main/main/account/urls.py
from django.urls import path
from .views import *

app_name = "account"
urlpatterns = [
    

    path('login/', login_views, name="login"),
    path('logout/', logout_views, name="logout"),

    path('profile/', profile_views, name="profile"),

    # user
    path("update/profile/", update_user_profile_views, name="update_user_profile"),
    path("change_password", change_password_views, name="change_password"),

    # only superuser
    path('users/', users_views, name="users"),
    path('add_user/', add_user_views, name="add_user"),
    path('delete_user/<str:username>', user_delete_views, name="user_delete"),
    path("edit_user/<str:username>", edit_user_views, name="edit_user"),
]

Web/main/main/dlp/urls.py
from django.urls import path
from .views import *

app_name = "dlp"
urlpatterns = [
    path('dashboard/', dashboard_views, name="dashboard"),
    path('policy/', policy_views, name="policy"),
    path('rules/', rules_views, name="rules"),
    path('logs/', logs_views, name="logs"),

    # only superuser
    path('add_policy/', add_policy_views, name="add_policy"),
    path('update_policy/<int:id>/', update_policy_views, name="update_policy"),
    path('delete_policy/<int:id>/', delete_policy_views, name="delete_policy"),

    path('add_rule/', add_rule_views, name="add_rule"),
    path('update_rule/<int:id>/', update_rule_views, name="update_rule"),
    path('delete_rule/<int:id>/', delete_rule_views, name="delete_rule"),

    path('update_log/<int:id>/', update_log_views, name="update_log"),
    path('delete_log/<int:id>/', delete_log_views, name="delete_log"),

    # export
    path('export/log/excel/', logs_export_excel_views, name="logs_export_excel"),
    path('export/log/csv/', logs_export_csv_views, name="logs_export_csv"),
]

Web/main/main/home/urls.py
from django.urls import path
from .views import *

app_name = "home"
urlpatterns = [
    path('', index_views, name="index"),
    path('about/', about_views, name="about"),
    path('contact/', contact_views, name="contact"),
]

Web/main/main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('dlp/', include('dlp.urls')),

]

Web/main/main/home/models.py
from django.db import models

# Create your models here.

Web/main/main/home/views.py
from django.shortcuts import render


def index_views(request):
    return render(request, "home/index.html")

def about_views(request):
    return render(request, "home/about.html")

def contact_views(request):
    return render(request, "home/contact.html")

Web/main/main/templates/base/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ISTEC-CENTER DLP</title>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/bootstrap5.2.0.css' %}" rel="stylesheet">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
        }

        @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
        }

        .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
        }

        .bi {
        vertical-align: -.125em;
        fill: currentColor;
        }

        .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
        }

        .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
        }
    </style>
    
</head>
    <body>
        <div class="container">

            {% include 'base/home/header.html' %}
            <main>
                <div class="container marketing">
                    {% block content %}
                    {% endblock content %}
                </div>
                {% include 'base/home/footer.html' %}
            </main>
        </div>

    </body>
</html>

Web/main/main/templates/base/home/carousel.html
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="bd-placeholder-img" width="100%" height="100%" src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(15).webp">

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="bd-placeholder-img" width="100%" height="100%" src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(15).webp">

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img class="bd-placeholder-img" width="100%" height="100%" src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(15).webp">

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

Web/main/main/templates/base/home/footer.html
  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2022 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

Web/main/main/templates/base/home/header.html
<header class="container">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">DLP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'home:contact' %}" class="nav-link">Contact</a>
            </li>
          </ul>
          {% if request.user.is_authenticated %}
            <div class="d-flex">
              <a href="{% url 'account:logout' %}" class="btn btn-outline-danger">Logout</a>
            </div>
            <div class="d-flex">
              <a href="{% url 'dlp:dashboard' %}" class="btn btn-outline-info ms-3">Dashboard</a>
            </div>
          {% else %}
            <div class="d-flex">
              <a href="{% url 'account:login' %}" class="btn btn-outline-light">Login</a>
            </div>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>