Web/main/main/dlp/urls.py
from django.urls import path
from .views import *

app_name = "dlp"
urlpatterns = [
    path('dashboard/', dashboard_views, name="dashboard"),
    path('policy/', policy_views, name="policy"),
    path('rules/', rules_views, name="rules"),
    path('logs/', logs_views, name="logs"),

    # only superuser
    path('add_policy/', add_policy_views, name="add_policy"),
    path('update_policy/<int:id>/', update_policy_views, name="update_policy"),
    path('delete_policy/<int:id>/', delete_policy_views, name="delete_policy"),

    path('add_rule/', add_rule_views, name="add_rule"),
    path('update_rule/<int:id>/', update_rule_views, name="update_rule"),
    path('delete_rule/<int:id>/', delete_rule_views, name="delete_rule"),

    path('update_log/<int:id>/', update_log_views, name="update_log"),
    path('delete_log/<int:id>/', delete_log_views, name="delete_log"),

    # export
    path('export/log/excel/', logs_export_excel_views, name="logs_export_excel"),
    path('export/log/csv/', logs_export_csv_views, name="logs_export_csv"),
]

Web/main/main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('dlp/', include('dlp.urls')),

]

Web/main/main/dlp/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.


class Logs(models.Model):
    file_path = models.CharField(
        max_length=500, verbose_name="File Path")
    event_type = models.CharField(max_length=100, verbose_name="Event Type")
    created_date = models.DateTimeField(
        verbose_name="Created Date", auto_now_add=True)

    def __str__(self):
        return self.event_type

    def get_update_url(self):
        return reverse('dlp:update_log', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('dlp:delete_log', kwargs={'id': self.id})


class Rule(models.Model):
    PERMISSION = [
        ('N', 'No Access'),
        ('F', 'Full Accsess'),
        ('M', 'Modify access'),
        ('RX', 'Read and execute access'),
        ('R', 'Read-only access'),
        ('W', 'Write-only access'),
    ]

    ACCSESS = [
        ('grant', 'grant'),
        ('deny', 'deny'),
        ('remove', 'remove'),
        ('setintegritylevel', 'setintegritylevel'),
    ]

    name = models.CharField(max_length=50, verbose_name="Rule Name")
    permission = models.CharField(
        default="F", choices=PERMISSION, max_length=50)
    accsess = models.CharField(default="grant", choices=ACCSESS, max_length=50)
    created_date = models.DateTimeField(
        verbose_name="Created Date", auto_now_add=True)

    def __str__(self):
        return f"{self.name} ---> {self.permission} ---> {self.accsess}"

    def get_update_url(self):
        return reverse('dlp:update_rule', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('dlp:delete_rule', kwargs={'id': self.id})


class Policy(models.Model):
    name = models.CharField(
        max_length=500, verbose_name="Policy Name")
    logs = models.ManyToManyField(
        Logs, related_name="policy_logs", blank=True)
    rule = models.OneToOneField(Rule, on_delete=models.CASCADE)
    created_date = models.DateTimeField(
        verbose_name="Created Date", auto_now_add=True)

    def __str__(self):
        return f"{self.name} ---> {self.rule}"

    def get_update_url(self):
        return reverse('dlp:update_policy', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('dlp:delete_policy', kwargs={'id': self.id})

Web/main/main/dlp/forms.py
from django import forms
from .models import Logs, Policy, Rule


class PolicyCreateForm(forms.ModelForm):

    class Meta:
        model = Policy
        fields = ['name', 'logs', 'rule']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
        }


class PolicyUpdateForm(forms.ModelForm):

    class Meta:
        model = Policy
        fields = ['name', 'logs', 'rule']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
        }


class LogUpdateForm(forms.ModelForm):

    class Meta:
        model = Logs
        fields = ['file_path', 'event_type']
        widgets = {
            'file_path': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'event_type': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
        }


class RuleCreateForm(forms.ModelForm):

    class Meta:
        model = Rule
        fields = ['name', 'permission', 'accsess']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'permission': forms.Select(),
            'accsess': forms.Select(),
        }


class RuleUpdateForm(forms.ModelForm):

    class Meta:
        model = Rule
        fields = ['name', 'permission', 'accsess']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'permission': forms.Select(),
            'accsess': forms.Select(),
        }

Web/main/main/dlp/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import LogUpdateForm, PolicyCreateForm, PolicyUpdateForm, RuleCreateForm, RuleUpdateForm
from .models import Logs, Policy, Rule

import csv
import xlwt

from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


@login_required
def dashboard_views(request):

    return render(request, "dlp/dashboard.html")


@login_required
def policy_views(request):
    policy = Policy.objects.all()
    context = {
        'policy': policy
    }
    return render(request, "dlp/policy.html", context)


@login_required
def rules_views(request):
    rules = Rule.objects.all()
    context = {
        'rules': rules
    }
    return render(request, "dlp/rules.html", context)


@login_required
def logs_views(request):
    log_list = Logs.objects.all()

    paginator = Paginator(log_list, 15)  # Show 15 contacts per page

    page = request.GET.get('q')
    try:
        logs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        logs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        logs = paginator.page(paginator.num_pages)

    query = request.GET.get('q')
    if query:
        logs = log_list.filter(
            Q(file_path__icontains=query) | Q(event_type__icontains=query)).distinct()
    context = {
        'logs': logs
    }
    return render(request, "dlp/logs.html", context)

# only superuser


@login_required
def add_policy_views(request):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    if request.method == 'POST':
        policy_form = PolicyCreateForm(request.POST)
        if policy_form.is_valid():
            policy_form.save()
            messages.success(request, 'Policy has been created!')
            return redirect('dlp:policy')
        else:
            return render(request, 'dlp/post/add_policy.html', {'form': policy_form})

    policy_form = PolicyCreateForm(request.POST)
    return render(request, "dlp/post/add_policy.html", {'form': policy_form})


@login_required
def update_policy_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")
    instance = Policy.objects.get(pk=id)
    policy_form = PolicyUpdateForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if policy_form.is_valid():
            policy_form.save()
            messages.success(request, 'Policy has been updated!', {
                             'form': policy_form})
            return redirect('dlp:policy')
        else:
            return render(request, 'dlp/post/update_policy.html', {'form': policy_form})

    return render(request, "dlp/post/update_policy.html", {'form': policy_form})


@login_required
def delete_policy_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    policy = Policy.objects.get(id=id)
    try:
        policy.delete()
        messages.success(request, "Policy has been successfully deleted.")
    except:
        messages.error(request, "Policy could not be deleted!")

    return redirect('dlp:policy')


@login_required
def add_rule_views(request):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")
    rule_form = RuleCreateForm(request.POST or None)

    if request.method == 'POST':
        if rule_form.is_valid():
            rule_form.save()
            messages.success(request, 'Rule has been created!')
            return redirect('dlp:rules')
        else:
            return render(request, 'dlp/post/add_rule.html', {'form': rule_form})

    return render(request, 'dlp/post/add_rule.html', {'form': rule_form})


@login_required
def update_rule_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    instance = Rule.objects.get(id=id)
    rule_form = RuleUpdateForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if rule_form.is_valid():
            rule_form.save()
            messages.success(request, 'Rule has been updated!')
            return redirect('dlp:rules')
        else:
            return render(request, 'dlp/post/update_rule.html', {'form': rule_form})

    return render(request, 'dlp/post/update_rule.html', {'form': rule_form})


@login_required
def delete_rule_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    rule = Rule.objects.get(id=id)
    try:
        rule.delete()
        messages.success(request, "Rule has been successfully deleted.")
    except:
        messages.error(request, "Rule could not be deleted!")

    return redirect('dlp:rules')


@login_required
def update_log_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    instance = Logs.objects.get(id=id)
    log_form = LogUpdateForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if log_form.is_valid():
            log_form.save()
            messages.success(request, 'Log has been updated!')
            return redirect('dlp:logs')
        else:
            return render(request, 'dlp/post/update_log.html', {'form': log_form})

    return render(request, 'dlp/post/update_log.html', {'form': log_form})


@login_required
def delete_log_views(request, id):
    if not request.user.is_superuser:
        return redirect("dlp:dashboard")

    log = Logs.objects.get(id=id)
    try:
        log.delete()
        messages.success(request, "Log has been successfully deleted.")
    except:
        messages.error(request, "Log could not be deleted!")

    return redirect('dlp:logs')

# export


def logs_export_csv_views(request):

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=Logs_' + \
        str(datetime.now()) + '.csv'

    writer = csv.writer(response)
    writer.writerow(['Date', 'Source', 'Rule Type', 'Details'])

    logs = Logs.objects.all()

    for log in logs:
        writer.writerow([log.created_date, log.file_path,
                        log.rule_type, log.event_type])

    return response


def logs_export_excel_views(request):

    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=Logs_' + \
        str(datetime.now()) + '.xls'

    wb = xlwt.Workbook(encoding='utf*8')
    ws = wb.add_sheet('Logs')
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['Date', 'Source', 'Rule Type', 'Details']

    logs = Logs.objects.all()
    #  ws.write([log.created_date, log.file_path, log.rule_type, log.event_type])
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    rows = Logs.objects.all().values_list(
        'created_date', 'file_path', 'rule_type', 'event_type')

    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, str(rows[col_num]), font_style)

    wb.save(response)

    return response

Web/main/main/templates/dlp/post/add_policy.html
{% extends 'base/admin/base.html' %}
{% block content %}

<style>
    /* The container must be positioned relative: */
    #id_rule {
    position: relative;
    font-family: Arial;
    }

    #id_rule select {
    display: none; /*hide original SELECT element: */
    }

    select {
    background-color: rgb(255, 30, 71);
    }

    /* Style the arrow inside the select element: */
    select:after {
    position: absolute;
    content: "";
    top: 14px;
    right: 10px;
    width: 0;
    height: 0;
    border: 6px solid transparent;
    border-color: #fff transparent transparent transparent;
    }

    /* Point the arrow upwards when the select box is open (active): */
    select.select-arrow-active:after {
    border-color: transparent transparent #fff transparent;
    top: 7px;
    }

    /* style the items (options), including the selected item: */
    .select-items div,select {
    color: #ffffff;
    padding: 8px 16px;
    border: 1px solid transparent;
    border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
    cursor: pointer;
    }

    /* Style items (options): */
    .select-items {
    position: absolute;
    background-color: DodgerBlue;
    top: 100%;
    left: 0;
    right: 0;
    z-index: 99;
    }

    /* Hide the items when the select box is closed: */
    .select-hide {
    display: none;
    }

    .select-items div:hover, .same-as-selected {
    background-color: rgba(0, 0, 0, 0.1);
    }
</style>
<!-- Page Wrapper -->
<div id="wrapper">
    {% include 'base/admin/sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            {% include 'base/admin/topbar.html' %}

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                {% include 'base/message.html' %}

                <h1 class="h3 mb-2 text-gray-800">ADD POLICY</h1>
                <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                        href="https://datatables.net">official DataTables documentation</a>.</p>
                        <div class="col-lg-7">
                            <form class="user" method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <label for="exampleFormControlTextarea1" class="form-label ">Name</label>
                                        {{form.name}}
                                    </div>
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <label for="exampleFormControlTextarea1" class="form-label ">Logs</label>
                                        {{form.logs}}
                                    </div>
                                    
                                </div>
                                
                                
                                <div class="form-group">
                                    <label for="exampleFormControlTextarea1" class="form-label ">Rule</label>
                                    {{form.rule}}
                                </div>
                                
                               
                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                    Create
                                </button>
                            </form>
                        </div>
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        {% include 'base/admin/footer.html' %}

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

{% endblock content %}

Web/main/main/templates/dlp/post/add_rule.html
{% extends 'base/admin/base.html' %}
{% block content %}
<style>
    /* The container must be positioned relative: */
    #id_rule {
    position: relative;
    font-family: Arial;
    }

    #id_rule select {
    display: none; /*hide original SELECT element: */
    }

    select {
    background-color: rgb(255, 30, 71);
    }

    /* Style the arrow inside the select element: */
    select:after {
    position: absolute;
    content: "";
    top: 14px;
    right: 10px;
    width: 0;
    height: 0;
    border: 6px solid transparent;
    border-color: #fff transparent transparent transparent;
    }

    /* Point the arrow upwards when the select box is open (active): */
    select.select-arrow-active:after {
    border-color: transparent transparent #fff transparent;
    top: 7px;
    }

    /* style the items (options), including the selected item: */
    .select-items div,select {
    color: #ffffff;
    padding: 8px 16px;
    border: 1px solid transparent;
    border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
    cursor: pointer;
    }

    /* Style items (options): */
    .select-items {
    position: absolute;
    background-color: DodgerBlue;
    top: 100%;
    left: 0;
    right: 0;
    z-index: 99;
    }

    /* Hide the items when the select box is closed: */
    .select-hide {
    display: none;
    }

    .select-items div:hover, .same-as-selected {
    background-color: rgba(0, 0, 0, 0.1);
    }
</style>
<!-- Page Wrapper -->
<div id="wrapper">
    {% include 'base/admin/sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            {% include 'base/admin/topbar.html' %}

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                {% include 'base/message.html' %}

                <h1 class="h3 mb-2 text-gray-800">ADD RULE</h1>
                <p class="mb-4">ICACLS <br>
                    Displays or modifies discretionary access control lists (DACLs) on specified files, and applies stored DACLs to files in specified directories.<!-- Button trigger modal -->
                    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        ICACLS HELP
                    </button>
                </p>
                <div class="col-lg-7">
                    <form class="user" method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <label for="exampleFormControlTextarea1" class="form-label ">Name</label>
                                {{form.name}}
                            </div>
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <label for="exampleFormControlTextarea1" class="form-label ">Permission</label>
                                {{form.permission}}
                            </div>

                        </div>


                        <div class="form-group">
                            <label for="exampleFormControlTextarea1" class="form-label ">Accsess</label>
                            {{form.accsess}}
                        </div>


                        <button type="submit" class="btn btn-primary btn-user btn-block">
                            ADD
                        </button>
                    </form>
                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        {% include 'base/admin/footer.html' %}

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">ICACLS HELP</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="text-start fs-5 fw-bolder">
                ICACLS name [/grant[:r] Sid:perm[...]]
                [/deny Sid:perm [...]]
                [/remove[:g|:d]] Sid[...]] [/T] [/C] [/L] [/Q]
                [/setintegritylevel Level:policy[...]]</p>
                
                <p class="text-start fs-5 fw-bold">
                /grant[:r] Sid:perm grants the specified user access rights. With :r,
                the permissions replace any previously granted explicit permissions.
                Without :r, the permissions are added to any previously granted
                explicit permissions.</p>
                
                <p class="text-start fs-5 fw-bold">
                /deny Sid:perm explicitly denies the specified user access rights.
                An explicit deny ACE is added for the stated permissions and
                the same permissions in any explicit grant are removed.</p>
                
                <p class="text-start fs-5 fw-bold">
                /remove[:[g|d]] Sid removes all occurrences of Sid in the ACL. With
                :g, it removes all occurrences of granted rights to that Sid. With
                :d, it removes all occurrences of denied rights to that Sid.</p>
                
                <p class="text-start fs-5 fw-bold">
                /setintegritylevel [(CI)(OI)]Level explicitly adds an integrity
                ACE to all matching files. The level is to be specified as one
                of:
                L[ow]
                M[edium]
                H[igh]
                Inheritance options for the integrity ACE may precede the level
                and are applied only to directories.</p>

                <p class="text-start fs-5 fw-bold">
                perm is a permission mask and can be specified in one of two forms:
                a sequence of simple rights:
                N - no access
                F - full access
                M - modify access
                RX - read and execute access
                R - read-only access
                W - write-only access
                D - delete access</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Web/main/main/templates/dlp/post/update_log.html
{% extends 'base/admin/base.html' %}
{% block content %}

<!-- Page Wrapper -->
<div id="wrapper">
    {% include 'base/admin/sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            {% include 'base/admin/topbar.html' %}

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                {% include 'base/message.html' %}

                <h1 class="h3 mb-2 text-gray-800">UPDATE LOG</h1>
                <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                        href="https://datatables.net">official DataTables documentation</a>.</p>
                        <div class="col-lg-7">
                            <form class="user" method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <label for="exampleFormControlTextarea1" class="form-label ">File Path</label>
                                        {{form.file_path}}
                                    </div>
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <label for="exampleFormControlTextarea1" class="form-label ">Event Type</label>
                                        {{form.event_type}}
                                    </div>
                                    
                                </div>
                               
                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                    UPDATE
                                </button>
                            </form>
                        </div>
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        {% include 'base/admin/footer.html' %}

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

{% endblock content %}

Web/main/main/templates/dlp/post/update_policy.html
{% extends 'base/admin/base.html' %}
{% block content %}
<style>
    /* The container must be positioned relative: */
    #id_rule {
    position: relative;
    font-family: Arial;
    }

    #id_rule select {
    display: none; /*hide original SELECT element: */
    }

    select {
    background-color: rgb(255, 30, 71);
    }

    /* Style the arrow inside the select element: */
    select:after {
    position: absolute;
    content: "";
    top: 14px;
    right: 10px;
    width: 0;
    height: 0;
    border: 6px solid transparent;
    border-color: #fff transparent transparent transparent;
    }

    /* Point the arrow upwards when the select box is open (active): */
    select.select-arrow-active:after {
    border-color: transparent transparent #fff transparent;
    top: 7px;
    }

    /* style the items (options), including the selected item: */
    .select-items div,select {
    color: #ffffff;
    padding: 8px 16px;
    border: 1px solid transparent;
    border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
    cursor: pointer;
    }

    /* Style items (options): */
    .select-items {
    position: absolute;
    background-color: DodgerBlue;
    top: 100%;
    left: 0;
    right: 0;
    z-index: 99;
    }

    /* Hide the items when the select box is closed: */
    .select-hide {
    display: none;
    }

    .select-items div:hover, .same-as-selected {
    background-color: rgba(0, 0, 0, 0.1);
    }
</style>
<!-- Page Wrapper -->
<div id="wrapper">
    {% include 'base/admin/sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            {% include 'base/admin/topbar.html' %}

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                {% include 'base/message.html' %}

                <h1 class="h3 mb-2 text-gray-800">UDATE POLICY</h1>
                <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                    For more information about DataTables, please visit the <a target="_blank"
                        href="https://datatables.net">official DataTables documentation</a>.</p>
                        <div class="col-lg-7">
                            <form class="user" method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <label for="exampleFormControlTextarea1" class="form-label ">Name</label>
                                        {{form.name}}
                                    </div>
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <label for="exampleFormControlTextarea1" class="form-label ">Logs</label>
                                        {{form.logs}}
                                    </div>
                                    
                                </div>
                                
                                
                                <div class="form-group">
                                    <label for="exampleFormControlTextarea1" class="form-label ">Rule</label>
                                    {{form.rule}}
                                </div>
                                
                               
                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                    Update
                                </button>
                            </form>
                        </div>
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        {% include 'base/admin/footer.html' %}

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

{% endblock content %}